#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B verify --file pom.xml
          - docker build -t mit/elasticapi .
          - pipe: atlassian/aws-ecr-push-image:1.4.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${REGION}
              IMAGE_NAME: mit/elasticapi
        services:
          - docker
    - step:
        name: Deploy
        deployment: dev
        script:
          - sed -i "s|{{image}}|$ECR/mit/elasticapi:latest|g" deployment.yml
          - pipe: atlassian/aws-eks-kubectl-run:1.3.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${REGION}
              CLUSTER_NAME: $CLUSTER_NAME
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment.yml"
              DEBUG: "true"